config/routes.rb
Rails.application.routes.draw do
  get '/warriors/name/:name', to: 'warriors#name'
  resources :equipment_lists
  resources :warriors
  resources :scenarios
  resources :mutations
  resources :skills
  resources :spells
  resources :equipment
  resources :armours
  resources :special_rules
  resources :weapons
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/armour.rb
class Armour < ApplicationRecord
    has_many :armour_special_rules
    has_many :special_rules, through: :armour_special_rules
    has_many :equipment_list_armours
    has_many :equipment_lists, through: :equipment_list_armours
end

app/models/armour_special_rule.rb
class ArmourSpecialRule < ApplicationRecord
    belongs_to :special_rule
    belongs_to :armour
end

app/models/equipment.rb
class Equipment < ApplicationRecord
    has_many :equipment_list_equipments
    has_many :equipment_lists, through: :equipment_list_equipments
end

app/models/equipment_list.rb
class EquipmentList < ApplicationRecord
    has_many :equipment_list_armours
    has_many :armours, through: :equipment_list_armours

    has_many :equipment_list_weapons
    has_many :weapons, through: :equipment_list_weapons
    
    has_many :equipment_list_equipments
    has_many :equipments, through: :equipment_list_equipments

    has_many :warriors_equipment_lists
    has_many :warriors, through: :warriors_equipment_lists
end

app/models/mutation.rb
class Mutation < ApplicationRecord
end

app/models/scenario.rb
class Scenario < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
    has_many :warrior_skills
    has_many :warriors, through: :warrior_skills
end

app/models/special_rule.rb
class SpecialRule < ApplicationRecord
    has_many :weapon_special_rules
    has_many :weapons, through: :weapon_special_rules
    has_many :armour_special_rules
    has_many :armours, through: :armour_special_rules

end

app/models/spell.rb
class Spell < ApplicationRecord
end

app/models/warrior.rb
class Warrior < ApplicationRecord
    has_many :warrior_skills
    has_many :skills, through: :warrior_skills

    has_many :warriors_equipment_lists
    has_many :equipment_lists, through: :warriors_equipment_lists

    has_many :armours, through: :equipment_lists
    has_many :weapons, through: :equipment_lists
    has_many :equipments, through: :equipment_lists
end

app/models/warrior_skill.rb
class WarriorSkill < ApplicationRecord
    belongs_to :warrior
    belongs_to :skill
end

app/models/weapon.rb
class Weapon < ApplicationRecord
    has_many :weapon_special_rules
    has_many :special_rules, through: :weapon_special_rules

    has_many :equipment_list_weapons
    has_many :equipment_lists, through: :equipment_list_weapons
end

app/controllers/armours_controller.rb
class ArmoursController < ApplicationController
  before_action :set_armour, only: %i[ show ]

  # GET /armours or /armours.json
  def index
    @armours = Armour.all
    render :json => @armours, :include => :special_rules
  end

  # GET /armours/1 or /armours/1.json
  def show
    render :json => @armour, :include => :special_rules
  end

  # GET /armours/new
  def new
    @armour = Armour.new
  end

  # GET /armours/1/edit
  def edit
  end

  # POST /armours or /armours.json
  def create
    @armour = Armour.new(armour_params)

    respond_to do |format|
      if @armour.save
        format.html { redirect_to @armour, notice: "Armour was successfully created." }
        format.json { render :show, status: :created, location: @armour }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @armour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /armours/1 or /armours/1.json
  def update
    respond_to do |format|
      if @armour.update(armour_params)
        format.html { redirect_to @armour, notice: "Armour was successfully updated." }
        format.json { render :show, status: :ok, location: @armour }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @armour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /armours/1 or /armours/1.json
  def destroy
    @armour.destroy
    respond_to do |format|
      format.html { redirect_to armours_url, notice: "Armour was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_armour
      @armour = Armour.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def armour_params
      params.require(:armour).permit(:name, :saving_throw, :cost, :rarity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/armours_helper.rb
module ArmoursHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/mutations_helper.rb
module MutationsHelper
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/helpers/warriors_helper.rb
module WarriorsHelper
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/armours/_form.html.erb
<%= form_with(model: armour) do |form| %>
  <% if armour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(armour.errors.count, "error") %> prohibited this armour from being saved:</h2>

      <ul>
        <% armour.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :save %>
    <%= form.text_field :save %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.text_field :cost %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/armours/edit.html.erb
<h1>Editing Armour</h1>

<%= render 'form', armour: @armour %>

<%= link_to 'Show', @armour %> |
<%= link_to 'Back', armours_path %>

app/views/armours/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Armours</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Save</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @armours.each do |armour| %>
      <tr>
        <td><%= armour.name %></td>
        <td><%= armour.save %></td>
        <td><%= armour.cost %></td>
        <td><%= link_to 'Show', armour %></td>
        <td><%= link_to 'Edit', edit_armour_path(armour) %></td>
        <td><%= link_to 'Destroy', armour, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Armour', new_armour_path %>

app/views/armours/new.html.erb
<h1>New Armour</h1>

<%= render 'form', armour: @armour %>

<%= link_to 'Back', armours_path %>

app/views/armours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @armour.name %>
</p>

<p>
  <strong>Save:</strong>
  <%= @armour.save %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @armour.cost %>
</p>

<%= link_to 'Edit', edit_armour_path(@armour) %> |
<%= link_to 'Back', armours_path %>