config/routes.rb
Rails.application.routes.draw do
  get '/warriors/name/:name', to: 'warriors#name'
  resources :equipment_lists
  resources :warriors
  resources :scenarios
  resources :mutations
  resources :skills
  resources :spells
  resources :equipment
  resources :armours
  resources :special_rules
  resources :weapons
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/armour.rb
class Armour < ApplicationRecord
    has_many :armour_special_rules
    has_many :special_rules, through: :armour_special_rules
    has_many :equipment_list_armours
    has_many :equipment_lists, through: :equipment_list_armours
end

app/models/armour_special_rule.rb
class ArmourSpecialRule < ApplicationRecord
    belongs_to :special_rule
    belongs_to :armour
end

app/models/equipment.rb
class Equipment < ApplicationRecord
    has_many :equipment_list_equipments
    has_many :equipment_lists, through: :equipment_list_equipments
end

app/models/equipment_list.rb
class EquipmentList < ApplicationRecord
    has_many :equipment_list_armours
    has_many :armours, through: :equipment_list_armours

    has_many :equipment_list_weapons
    has_many :weapons, through: :equipment_list_weapons
    
    has_many :equipment_list_equipments
    has_many :equipments, through: :equipment_list_equipments

    has_many :warriors_equipment_lists
    has_many :warriors, through: :warriors_equipment_lists
end

app/models/mutation.rb
class Mutation < ApplicationRecord
end

app/models/scenario.rb
class Scenario < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
    has_many :warrior_skills
    has_many :warriors, through: :warrior_skills
end

app/models/special_rule.rb
class SpecialRule < ApplicationRecord
    has_many :weapon_special_rules
    has_many :weapons, through: :weapon_special_rules
    has_many :armour_special_rules
    has_many :armours, through: :armour_special_rules

end

app/models/spell.rb
class Spell < ApplicationRecord
end

app/models/warrior.rb
class Warrior < ApplicationRecord
    has_many :warrior_skills
    has_many :skills, through: :warrior_skills

    has_many :warriors_equipment_lists
    has_many :equipment_lists, through: :warriors_equipment_lists

    has_many :armours, through: :equipment_lists
    has_many :weapons, through: :equipment_lists
    has_many :equipments, through: :equipment_lists
end

app/models/warrior_skill.rb
class WarriorSkill < ApplicationRecord
    belongs_to :warrior
    belongs_to :skill
end

app/models/weapon.rb
class Weapon < ApplicationRecord
    has_many :weapon_special_rules
    has_many :special_rules, through: :weapon_special_rules

    has_many :equipment_list_weapons
    has_many :equipment_lists, through: :equipment_list_weapons
end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
  before_action :set_spell, only: %i[ show ]

  # GET /spells or /spells.json
  def index
    @spells = Spell.all
    render :json => @spells
  end

  # GET /spells/1 or /spells/1.json
  def show
    render :json => @spell
  end

  # GET /spells/new
  def new
    @spell = Spell.new
  end

  # GET /spells/1/edit
  def edit
  end

  # POST /spells or /spells.json
  def create
    @spell = Spell.new(spell_params)

    respond_to do |format|
      if @spell.save
        format.html { redirect_to @spell, notice: "Spell was successfully created." }
        format.json { render :show, status: :created, location: @spell }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @spell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spells/1 or /spells/1.json
  def update
    respond_to do |format|
      if @spell.update(spell_params)
        format.html { redirect_to @spell, notice: "Spell was successfully updated." }
        format.json { render :show, status: :ok, location: @spell }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @spell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spells/1 or /spells/1.json
  def destroy
    @spell.destroy
    respond_to do |format|
      format.html { redirect_to spells_url, notice: "Spell was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spell
      @spell = Spell.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def spell_params
      params.require(:spell).permit(:school, :name, :difficulty, :description, :number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/armours_helper.rb
module ArmoursHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/mutations_helper.rb
module MutationsHelper
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/helpers/warriors_helper.rb
module WarriorsHelper
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/spells/_form.html.erb
<%= form_with(model: spell) do |form| %>
  <% if spell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spell.errors.count, "error") %> prohibited this spell from being saved:</h2>

      <ul>
        <% spell.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :school %>
    <%= form.text_field :school %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :difficulty %>
    <%= form.text_field :difficulty %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/spells/edit.html.erb
<h1>Editing Spell</h1>

<%= render 'form', spell: @spell %>

<%= link_to 'Show', @spell %> |
<%= link_to 'Back', spells_path %>

app/views/spells/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Spells</h1>

<table>
  <thead>
    <tr>
      <th>School</th>
      <th>Name</th>
      <th>Difficulty</th>
      <th>Description</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spells.each do |spell| %>
      <tr>
        <td><%= spell.school %></td>
        <td><%= spell.name %></td>
        <td><%= spell.difficulty %></td>
        <td><%= spell.description %></td>
        <td><%= spell.number %></td>
        <td><%= link_to 'Show', spell %></td>
        <td><%= link_to 'Edit', edit_spell_path(spell) %></td>
        <td><%= link_to 'Destroy', spell, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Spell', new_spell_path %>

app/views/spells/new.html.erb
<h1>New Spell</h1>

<%= render 'form', spell: @spell %>

<%= link_to 'Back', spells_path %>

app/views/spells/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>School:</strong>
  <%= @spell.school %>
</p>

<p>
  <strong>Name:</strong>
  <%= @spell.name %>
</p>

<p>
  <strong>Difficulty:</strong>
  <%= @spell.difficulty %>
</p>

<p>
  <strong>Description:</strong>
  <%= @spell.description %>
</p>

<p>
  <strong>Number:</strong>
  <%= @spell.number %>
</p>

<%= link_to 'Edit', edit_spell_path(@spell) %> |
<%= link_to 'Back', spells_path %>