config/routes.rb
Rails.application.routes.draw do
  get '/warriors/name/:name', to: 'warriors#name'
  resources :equipment_lists
  resources :warriors
  resources :scenarios
  resources :mutations
  resources :skills
  resources :spells
  resources :equipment
  resources :armours
  resources :special_rules
  resources :weapons
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/armour.rb
class Armour < ApplicationRecord
    has_many :armour_special_rules
    has_many :special_rules, through: :armour_special_rules
    has_many :equipment_list_armours
    has_many :equipment_lists, through: :equipment_list_armours
end

app/models/equipment.rb
class Equipment < ApplicationRecord
    has_many :equipment_list_equipments
    has_many :equipment_lists, through: :equipment_list_equipments
end

app/models/equipment_list.rb
class EquipmentList < ApplicationRecord
    has_many :equipment_list_armours
    has_many :armours, through: :equipment_list_armours

    has_many :equipment_list_weapons
    has_many :weapons, through: :equipment_list_weapons
    
    has_many :equipment_list_equipments
    has_many :equipments, through: :equipment_list_equipments

    has_many :warriors_equipment_lists
    has_many :warriors, through: :warriors_equipment_lists
end

app/models/mutation.rb
class Mutation < ApplicationRecord
end

app/models/scenario.rb
class Scenario < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
    has_many :warrior_skills
    has_many :warriors, through: :warrior_skills
end

app/models/special_rule.rb
class SpecialRule < ApplicationRecord
    has_many :weapon_special_rules
    has_many :weapons, through: :weapon_special_rules
    has_many :armour_special_rules
    has_many :armours, through: :armour_special_rules

end

app/models/spell.rb
class Spell < ApplicationRecord
end

app/models/warrior.rb
class Warrior < ApplicationRecord
    has_many :warrior_skills
    has_many :skills, through: :warrior_skills

    has_many :warriors_equipment_lists
    has_many :equipment_lists, through: :warriors_equipment_lists

    has_many :armours, through: :equipment_lists
    has_many :weapons, through: :equipment_lists
    has_many :equipments, through: :equipment_lists
end

app/models/warrior_skill.rb
class WarriorSkill < ApplicationRecord
    belongs_to :warrior
    belongs_to :skill
end

app/models/weapon.rb
class Weapon < ApplicationRecord
    has_many :weapon_special_rules
    has_many :special_rules, through: :weapon_special_rules

    has_many :equipment_list_weapons
    has_many :equipment_lists, through: :equipment_list_weapons
end

app/controllers/equipment_lists_controller.rb
class EquipmentListsController < ApplicationController
  before_action :set_equipment_list, only: %i[ show edit update destroy ]

  # GET /equipment_lists or /equipment_lists.json
  def index
    @equipment_lists = EquipmentList.all
    render :json => @equipment_lists, :include => [:weapons, :armours, :equipments]
  end

  # GET /equipment_lists/1 or /equipment_lists/1.json
  def show
    render :json => @equipment_list, :include => [:weapons, :armours, :equipments]
  end

  # GET /equipment_lists/new
  def new
    @equipment_list = EquipmentList.new
  end

  # GET /equipment_lists/1/edit
  def edit
  end

  # POST /equipment_lists or /equipment_lists.json
  def create
    @equipment_list = EquipmentList.new(equipment_list_params)

    respond_to do |format|
      if @equipment_list.save
        format.html { redirect_to @equipment_list, notice: "Equipment list was successfully created." }
        format.json { render :show, status: :created, location: @equipment_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @equipment_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipment_lists/1 or /equipment_lists/1.json
  def update
    respond_to do |format|
      if @equipment_list.update(equipment_list_params)
        format.html { redirect_to @equipment_list, notice: "Equipment list was successfully updated." }
        format.json { render :show, status: :ok, location: @equipment_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @equipment_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment_lists/1 or /equipment_lists/1.json
  def destroy
    @equipment_list.destroy
    respond_to do |format|
      format.html { redirect_to equipment_lists_url, notice: "Equipment list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipment_list
      @equipment_list = EquipmentList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def equipment_list_params
      params.require(:equipment_list).permit(:name, :warband)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/armours_helper.rb
module ArmoursHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/equipment_lists_helper.rb
module EquipmentListsHelper
end

app/helpers/mutations_helper.rb
module MutationsHelper
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/helpers/warriors_helper.rb
module WarriorsHelper
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/equipment_lists/_form.html.erb
<%= form_with(model: equipment_list) do |form| %>
  <% if equipment_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(equipment_list.errors.count, "error") %> prohibited this equipment_list from being saved:</h2>

      <ul>
        <% equipment_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :warband %>
    <%= form.text_field :warband %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/equipment_lists/edit.html.erb
<h1>Editing Equipment List</h1>

<%= render 'form', equipment_list: @equipment_list %>

<%= link_to 'Show', @equipment_list %> |
<%= link_to 'Back', equipment_lists_path %>

app/views/equipment_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Equipment Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Warband</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @equipment_lists.each do |equipment_list| %>
      <tr>
        <td><%= equipment_list.name %></td>
        <td><%= equipment_list.warband %></td>
        <td><%= link_to 'Show', equipment_list %></td>
        <td><%= link_to 'Edit', edit_equipment_list_path(equipment_list) %></td>
        <td><%= link_to 'Destroy', equipment_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Equipment List', new_equipment_list_path %>

app/views/equipment_lists/new.html.erb
<h1>New Equipment List</h1>

<%= render 'form', equipment_list: @equipment_list %>

<%= link_to 'Back', equipment_lists_path %>

app/views/equipment_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @equipment_list.name %>
</p>

<p>
  <strong>Warband:</strong>
  <%= @equipment_list.warband %>
</p>

<%= link_to 'Edit', edit_equipment_list_path(@equipment_list) %> |
<%= link_to 'Back', equipment_lists_path %>