config/routes.rb
Rails.application.routes.draw do
  get '/warriors/name/:name', to: 'warriors#name'
  resources :equipment_lists
  resources :warriors
  resources :scenarios
  resources :mutations
  resources :skills
  resources :spells
  resources :equipment
  resources :armours
  resources :special_rules
  resources :weapons
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/armour.rb
class Armour < ApplicationRecord
    has_many :armour_special_rules
    has_many :special_rules, through: :armour_special_rules
    has_many :equipment_list_armours
    has_many :equipment_lists, through: :equipment_list_armours
end

app/models/armour_special_rule.rb
class ArmourSpecialRule < ApplicationRecord
    belongs_to :special_rule
    belongs_to :armour
end

app/models/equipment.rb
class Equipment < ApplicationRecord
    has_many :equipment_list_equipments
    has_many :equipment_lists, through: :equipment_list_equipments
end

app/models/equipment_list.rb
class EquipmentList < ApplicationRecord
    has_many :equipment_list_armours
    has_many :armours, through: :equipment_list_armours

    has_many :equipment_list_weapons
    has_many :weapons, through: :equipment_list_weapons
    
    has_many :equipment_list_equipments
    has_many :equipments, through: :equipment_list_equipments

    has_many :warriors_equipment_lists
    has_many :warriors, through: :warriors_equipment_lists
end

app/models/mutation.rb
class Mutation < ApplicationRecord
end

app/models/scenario.rb
class Scenario < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
    has_many :warrior_skills
    has_many :warriors, through: :warrior_skills
end

app/models/special_rule.rb
class SpecialRule < ApplicationRecord
    has_many :weapon_special_rules
    has_many :weapons, through: :weapon_special_rules
    has_many :armour_special_rules
    has_many :armours, through: :armour_special_rules

end

app/models/spell.rb
class Spell < ApplicationRecord
end

app/models/warrior.rb
class Warrior < ApplicationRecord
    has_many :warrior_skills
    has_many :skills, through: :warrior_skills

    has_many :warriors_equipment_lists
    has_many :equipment_lists, through: :warriors_equipment_lists

    has_many :armours, through: :equipment_lists
    has_many :weapons, through: :equipment_lists
    has_many :equipments, through: :equipment_lists
end

app/models/warrior_skill.rb
class WarriorSkill < ApplicationRecord
    belongs_to :warrior
    belongs_to :skill
end

app/models/weapon.rb
class Weapon < ApplicationRecord
    has_many :weapon_special_rules
    has_many :special_rules, through: :weapon_special_rules

    has_many :equipment_list_weapons
    has_many :equipment_lists, through: :equipment_list_weapons
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  before_action :set_scenario, only: %i[ show edit update destroy ]

  # GET /scenarios or /scenarios.json
  def index
    @scenarios = Scenario.all
    render :json => @scenarios
  end

  # GET /scenarios/1 or /scenarios/1.json
  def show
    render :json => @scenario
  end

  # GET /scenarios/new
  def new
    @scenario = Scenario.new
  end

  # GET /scenarios/1/edit
  def edit
  end

  # POST /scenarios or /scenarios.json
  def create
    @scenario = Scenario.new(scenario_params)

    respond_to do |format|
      if @scenario.save
        format.html { redirect_to @scenario, notice: "Scenario was successfully created." }
        format.json { render :show, status: :created, location: @scenario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scenarios/1 or /scenarios/1.json
  def update
    respond_to do |format|
      if @scenario.update(scenario_params)
        format.html { redirect_to @scenario, notice: "Scenario was successfully updated." }
        format.json { render :show, status: :ok, location: @scenario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scenarios/1 or /scenarios/1.json
  def destroy
    @scenario.destroy
    respond_to do |format|
      format.html { redirect_to scenarios_url, notice: "Scenario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scenario
      @scenario = Scenario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def scenario_params
      params.require(:scenario).permit(:name, :description, :terrain, :warbands, :starting, :ending, :experience, :wyrdstone, :special_rules)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/armours_helper.rb
module ArmoursHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/mutations_helper.rb
module MutationsHelper
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/helpers/warriors_helper.rb
module WarriorsHelper
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/scenarios/_form.html.erb
<%= form_with(model: scenario) do |form| %>
  <% if scenario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scenario.errors.count, "error") %> prohibited this scenario from being saved:</h2>

      <ul>
        <% scenario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :terrain %>
    <%= form.text_field :terrain %>
  </div>

  <div class="field">
    <%= form.label :warbands %>
    <%= form.text_field :warbands %>
  </div>

  <div class="field">
    <%= form.label :starting %>
    <%= form.text_field :starting %>
  </div>

  <div class="field">
    <%= form.label :ending %>
    <%= form.text_field :ending %>
  </div>

  <div class="field">
    <%= form.label :experience %>
    <%= form.text_field :experience %>
  </div>

  <div class="field">
    <%= form.label :wyrdstone %>
    <%= form.text_field :wyrdstone %>
  </div>

  <div class="field">
    <%= form.label :special_rules %>
    <%= form.text_field :special_rules %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scenarios/edit.html.erb
<h1>Editing Scenario</h1>

<%= render 'form', scenario: @scenario %>

<%= link_to 'Show', @scenario %> |
<%= link_to 'Back', scenarios_path %>

app/views/scenarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scenarios</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Terrain</th>
      <th>Warbands</th>
      <th>Starting</th>
      <th>Ending</th>
      <th>Experience</th>
      <th>Wyrdstone</th>
      <th>Special rules</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scenarios.each do |scenario| %>
      <tr>
        <td><%= scenario.name %></td>
        <td><%= scenario.description %></td>
        <td><%= scenario.terrain %></td>
        <td><%= scenario.warbands %></td>
        <td><%= scenario.starting %></td>
        <td><%= scenario.ending %></td>
        <td><%= scenario.experience %></td>
        <td><%= scenario.wyrdstone %></td>
        <td><%= scenario.special_rules %></td>
        <td><%= link_to 'Show', scenario %></td>
        <td><%= link_to 'Edit', edit_scenario_path(scenario) %></td>
        <td><%= link_to 'Destroy', scenario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scenario', new_scenario_path %>

app/views/scenarios/new.html.erb
<h1>New Scenario</h1>

<%= render 'form', scenario: @scenario %>

<%= link_to 'Back', scenarios_path %>

app/views/scenarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @scenario.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @scenario.description %>
</p>

<p>
  <strong>Terrain:</strong>
  <%= @scenario.terrain %>
</p>

<p>
  <strong>Warbands:</strong>
  <%= @scenario.warbands %>
</p>

<p>
  <strong>Starting:</strong>
  <%= @scenario.starting %>
</p>

<p>
  <strong>Ending:</strong>
  <%= @scenario.ending %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @scenario.experience %>
</p>

<p>
  <strong>Wyrdstone:</strong>
  <%= @scenario.wyrdstone %>
</p>

<p>
  <strong>Special rules:</strong>
  <%= @scenario.special_rules %>
</p>

<%= link_to 'Edit', edit_scenario_path(@scenario) %> |
<%= link_to 'Back', scenarios_path %>